session: redsun-mimir
engine: bluesky
frontend: pyqt
models:
  Mock1:
    plugin_name: test
    plugin_id: test
    sensor_shape: [100, 100]
    pixel_size: [1, 1]
controllers:
  AcquisitionController:
    plugin_name: test
    plugin_id: test
    timeout: 5.0
  DetectorController:
    plugin_name: test
    plugin_id: test
    timeout: 5.0
views:
  AcquisitionWidget:
    plugin_name: test
    plugin_id: test
    # doesn't have any effect;
    # used locally for testing
    position: center
  DetectorWidget:
    plugin_name: test
    plugin_id: test
    # doesn't have any effect;
    # used locally for testing
    position: center
