schema_version: 1.0
session: redsun-mimir
frontend: pyqt

storage:
  backend: zarr

devices:
  camera1:
    sensor_shape: [100, 100]
  motor:
    axis: [X, Y, Z]
    step_sizes:
      X: 100.0
      Y: 100.0
      Z: 100.0
    egu: um

presenters:
  median_ctrl:
    streams: [square_scan]
    hints: [buffer]
  det_ctrl:
    timeout: 5.0
  acq_ctrl:
    callbacks: [det_ctrl, median_ctrl]

views:
  acq_widget: {}
  img_widget: {}
  det_widget: {}
