schema_version: 1.0
session: redsun-mimir
frontend: pyqt

devices:
  stage:
    axis:
      - x
      - y
      - z
    step_sizes:
      x: 1.0
      y: 1.0
      z: 0.1
    egu: mm
    limits:
      x: [0.0, 100.0]
      y: [0.0, 100.0]
      z: [-5.0, 5.0]
  camera:
    sensor_shape: [512, 512]
    stage_name: stage
    world_scale: 4
    n_blobs: 40
  laser:
    wavelength: 532
    egu: mW
    intensity_range: [0, 100]
    step_size: 1

presenters:
  median_ctrl:
    streams: [square_scan]
    hints: [buffer]
  det_ctrl:
    timeout: 5.0
  acq_ctrl:
    callbacks:
      - det_ctrl
      - median_ctrl

views:
  acq_widget: {}
  img_widget: {}
  det_widget: {}
