schema_version: 1.0
session: redsun-mimir
frontend: pyqt

devices:
  stage:
    axis:
      - x
      - y
      - z
    step_sizes:
      x: 1.0
      y: 1.0
      z: 0.1
    egu: mm
    limits:
      x: [0.0, 100.0]
      y: [0.0, 100.0]
      z: [-5.0, 5.0]

presenters:
  ctrl:
    timeout: 5.0

views:
  widget: {}
