schema_version: 1.0
session: redsun-mimir
frontend: pyqt

devices:
  laser:
    wavelength: 532
    egu: mW
    intensity_range: [0, 100]
    step_size: 1

presenters:
  ctrl:
    timeout: 5.0

views:
  widget: {}
