schema: 1.0
session: redsun-mimir
frontend: pyqt

devices:
  led:
    alias: Mock LED
    wavelength: 300
    binary: true
    intensity_range: [0, 0]
  laser:
    alias: Mock laser
    wavelength: 650
    egu: mW
    intensity_range: [0, 100]
    step_size: 1

presenters:
  ctrl:
    timeout: 5.0

views:
  widget: {}
