schema: 1.0
session: redsun-mimir
frontend: pyqt

devices:
  camera1:
    alias: Mock1
    sensor_shape: [100, 100]
  camera2:
    alias: Mock2

presenters:
  ctrl:
    timeout: 5.0

views:
  widget: {}
