schema: 1.0
session: redsun-mimir
frontend: pyqt

devices:
  camera:
    sensor_shape: [100, 100]
  motor:
    axis:
      - X
      - Y
      - Z
    step_sizes:
      X: 100.0
      Y: 100.0
      Z: 100.0
    egu: um

presenters:
  median_ctrl: {}
  det_ctrl:
    timeout: 5.0
  acq_ctrl:
    timeout: 5.0
    callbacks:
      - DetectorPresenter
      - MedianPresenter

views:
  acq_widget: {}
  det_widget: {}
